
noise_words = {'of', 'in', 'at', 'the'}


def clean_string(x):
    ret = x.lower()
    ret = ''.join(w for w in ret.split() if w not in noise_words)
    ret = ret.replace(',', '')
    ret = ret.replace(' ', '')
    return ret


alternative_name_list = [['Bowling Green State University',
                          'Bowling Green State U'],
                         ['University Of Minnesota',
                          'Minnesota U',
                          'Minnesota',
                          'UMN',
                          'The University Of Minnesota',
                          'U Of Minnesota',
                          'University Of Minnesota Twin Cities',
                          'Twin Cities',
                          'University Of Minnesota, Twin Cities',
                          'University Of Minessota',
                          'The University Of Minnesota, Twin Cities'],
                         ['UC Berkeley',
                          'University Of California, Berkeley',
                          'University Of Berkeley',
                          'UCBerkeley',
                          'UCB',
                          'California Berkeley',
                          'UC, Berkeley',
                          'Berkeley',
                          'University Of California Berkeley',
                          'Uc Berkeley',
                          'Ucberkeley',
                          'U C Berkeley',
                          'University Of California At Berkeley'],
                         ['University Of Michigan, Ann Arbor',
                          'University Of Michigan',
                          'University Of Michigan Ann Arbor',
                          'Michigan, Ann Arbor',
                          'Michigan Ann Arbor',
                          'The University Of Michigan',
                          'Michigan',
                          'Michigan , Ann Arbor',
                          'The University Of Michigan, Ann Arbor',
                          'UM',
                          'U Of Michigan',
                          'U Michigan',
                          'University Of Michgan, Ann Arbor',
                          'University Of Michian Ann Arbor',
                          'Univ Of Mich, Ann Arbor',
                          'University Of Michigan , Ann Arbor'],
                         ['University Of Texas At Austin',
                          'University Of Texas, Austin',
                          'UT Austin',
                          'The University Of Texas At Austin',
                          'UT AUSTIN',
                          'UT At Austin'],
                         ['Penn State University',
                          'Penn State',
                          'Pen State',
                          'Pennsylvania State University',
                          'Penn State PSU'],
                         ['University Of Missouri',
                          'University Of Missouri',
                          'Missouri University',
                          'MIssouri University',
                          'University Of Missouri, Columbia'],
                         ['ETH Zurich',
                          'ETH'],
                         ['Univ Of Florida'],
                         ['NCSU',
                          'North Carolina State University',
                          'North Carolina State Univeristy',
                          'NC State',
                          'North Carolina State',
                          'University Of North Carolina',
                          'NC State University',
                          'North  Carolina State University',
                          'North Carilina State University',
                          'Ncsu',
                          'North Carolina Sate University'],
                         ['KU Leuven'],
                         ['University Of Virginia',
                          'UVA',
                          'The University Of Virginia',
                          'U Of Virginia',
                          'Virginia University'],
                         ['Virginia Tech',
                          'VT',
                          'VirginiaTech',
                          'Virginia Polytechnic Institute And State University'],
                         ['UBC',
                          'University Of British Columbia'],
                         ['University Of Georgia',
                          'UGA',
                          'The University Of Georgia',
                          'University Of Georgia Athens'],
                         ['University Of Notre Dame',
                          'Notre Dame',
                          'U Of Notre Dame'],
                         ['Harvard University',
                          'Harvard',
                          'Harvard Graduate Schol Of Arts And Sciences',
                          'Harvard Graduate School Of Arts And Sciences',
                          'Harvard University Graduate School Of Arts And Sciences',
                          'Havard',
                          'Harvard University Graduate'],
                         ['Columbia University',
                          'Columbia',
                          'Columbia',
                          'Columbia GSAS'],
                         ['University Of Florida',
                          'UFlorida'],
                         ['Duke',
                          'Duke University',
                          'Duke Univesity'],
                         ['Stanford University',
                          'Stanford',
                          'Stanford Univeristy',
                          'Stanforduniversity'],
                         ['University Of Wisconsin, Madison',
                          'University Of Wisconsin Madison',
                          'University Of Wisconsin',
                          'University Of Wisconsin At Madison',
                          'UW Madison',
                          'Wisconsin',
                          'University If Wisconsin, Madison',
                          'U Of Wisconsin, Madison',
                          'Wisconsin Madison',
                          'UWisconsin Madison',
                          'Wisconsin At Madison'],
                         ['Oregon State University',
                          'Oregon State UNiversity'],
                         ['Purdue University',
                          'Purdue',
                          'Purdue  University',
                          'Purdue University, West Lafayette'],
                         ['Rice University',
                          'Rice',
                          'Rice Universiry'],
                         ['UTHSC'],
                         ['University Of Washington',
                          'U Washington, Seattle',
                          'U Of Washington',
                          'UW Seattle',
                          'University Of Washington Seattle',
                          'University Washington Seattle',
                          'University Of Washing',
                          'University Of Washington, Seattle',
                          'University Of Washington, Seatle',
                          'U Of Washington Seattle',
                          'Washington University'],
                         ['Washington University In St Louis'],
                         ['University Of Chicago',
                          'U Chicago',
                          'Chicago University',
                          'U Of Chicago',
                          'The University Of Chicago',
                          'University Of Chigago',
                          'Chicago',
                          'Uchicago',
                          'Universoty Of Chicago',
                          'Unversity Of Chicago'],
                         ['University Of Arizona',
                          'The University Of Arizona'],
                         ['Carnegie Mellon',
                          'Carnegie Mellon University',
                          'CMU',
                          'Canegie Mellon',
                          'Cmu',
                          'Carbegie Mellon University'],
                         ['Cornell University',
                          'Cornell',
                          'Conrell'],
                         ['Yale',
                          'Yale University',
                          'Yale GASA',
                          'Yale School Of Arts And Sciences',
                          'Yale Graduate School Of Arts And Sciences',
                          'Yale Graduate School Of Arts And SciencesYale University',
                          'Yale School Of Engineering And Applied Science'],
                         ['Portland State University'],
                         ['University Of North Carolina At Chapel Hill',
                          'UNC',
                          'Chapel Hill',
                          'University Of North Carolina Chapel Hill',
                          'UNC Chapel Hill',
                          'University Of Carolina At Chapel Hill',
                          'University Of North Carolina, Chapel Hill'],
                         ['University Of Pennsylvania',
                          'University Of Pennsylvania Warton School',
                          'UPenn Wharton',
                          'Wharton University Of Pennsylvania',
                          'University Of Pennsylvania Wharton',
                          'Wharton',
                          'University Of Pennsylvania, The Wharton School',
                          'The Wharton School'],
                         ['UIUC',
                          'Uiuc',
                          'University Of Illinois At U',
                          'University Of Illinois At Urbana Champaign',
                          'University Of Illinois',
                          'Univerity Of Illinois, Urbana Champaign',
                          'University Of Illinois, Urbana Champaign'],
                         ['University Of Iowa',
                          'The University Of Iowa',
                          'U Of Iowa',
                          'Iowa University'],
                         ['Ohio State University',
                          'The Ohio State University',
                          'Ohio State',
                          'OhioState',
                          'Ohio State U',
                          'OSU',
                          'Ohio State Univ'],
                         ['National Autonomous University Of Mexico'],
                         ['McMaster University',
                          'Mcmaster University',
                          'Mcmaster',
                          'McMaster'],
                         ['Iowa State',
                          'Iowa State University',
                          'Iowa State U',
                          'ISU'],
                         ['University Of California, Riverside',
                          'University California Riverside',
                          'University Of California Riverside UCR',
                          'UC, Riverside'],
                         ['McGill University'],
                         ['Oxford',
                          'Oxford University',
                          'University Of Oxford'],
                         ['Colorado State University',
                          'Colorado State U',
                          'Colorado State University'],
                         ['University Of California Irvine',
                          'UC Irvine',
                          'University Of California, Irvine',
                          'University Of Califonia,Irvine'],
                         ['University Of Arkansas',
                          'University Of Arkansas Fayetteville'],
                         ['LSE',
                          'London School Of Economics'],
                         ['San Jose State'],
                         ['UCLA',
                          'University Of California Los Angeles'],
                         ['University Of Manitoba'],
                         ['University Of Waterloo'],
                         ['rrgia State University',
                          'Waterloo U'],
                         ['George Washington University',
                          'The George Washington University',
                          'George Washington',
                          'George Washington Statsitics',
                          'George Washington U',
                          'GWU',
                          'George Wahington University',
                          'George Washington Universtiy'],
                         ['Rutgers',
                          'Rutgers University New Brunswick',
                          'Rutgers University',
                          'University Of Rutgers',
                          'Rutgers University, New Brunswick'],
                         ['California State University, Long Beach'],
                         ['University Of Toronto',
                          'The University Of Toronto'],
                         ['Michigan State University',
                          'Michigan State',
                          'MSU'],
                         ['Baylor University',
                          'Baylor U'],
                         ['University Of California, Davis',
                          'UC Davis'],
                         ['USC',
                          'University Of Southern California',
                          'Usc',
                          'U Of South California',
                          'USC University Of Southern California'],
                         ['Georgia Tech',
                          'GIT'],
                         ['Boston U',
                          'Boston University',
                          'BU'],
                         ['U Of Kentucky',
                          'University Of Kentucky'],
                         ['U Of Texas, Dallas',
                          'University Of Texas At Dallas',
                          'UT Dallas'],
                         ['Clemson University'],
                         ['Northwestern University',
                          'Northwestern',
                          'Northwestern U'],
                         ['University Of Connecticut',
                          'UConn',
                          'U Of Connecticut',
                          'U Connecticut',
                          'University Of Connecticut, Storrs'],
                         ['Florida State University',
                          'Florida State',
                          'Florida State Univeristy'],
                         ['Kansas State University'],
                         ['IUPUI'],
                         ['University Of Cambridge'],
                         ['Colorado School Of Mines'],
                         ['Stony Brook University',
                          'Stony Brook U',
                          'Stony Brook',
                          'SUNY Stony Brook',
                          'Stony Brook SUNY',
                          'Suny Stoney Brook',
                          'SUNY SB'],
                         ['Johns Hopkins University',
                          'Johns Hopkins',
                          'John Hopkins University',
                          'John Hopkins'],
                         ['WPI'],
                         ['University Of New Mexico'],
                         ['University Of Massachusetts Amherst',
                          'UMASS Amherst',
                          'UMass Amherst'],
                         ['University of Massachusetts Boston',
                          'UMASS Boston',
                          'Umass Boston'],
                         ['Uppsala University'],
                         ['Simon Fraser University SFU',
                          'Simon Fraser SFU',
                          'Simon Fraser University'],
                         ['University Of California Santa Barbara',
                          'UCSB',
                          'UC Santa Barabara',
                          'UC Santa Barbara',
                          'UC Santa Barbara',
                          'University Of California, Santa Barbara'],
                         ['San Diego State University'],
                         ['University Of Western Ontario',
                          'Western Ontario'],
                         ['Teachers College',
                          'Columbia University Teachers College',
                          'Columbia University, Teachers College'],
                         ['University Of South Carolina',
                          'U Of South Carolina',
                          'South Carolina',
                          'Unviersity Of South Carolina',
                          'The University Of South Carolina',
                          'University Of South Caroline'],
                         ['Queens University'],
                         ['Michigan Technological University'],
                         ['University Of Southampton'],
                         ['University Of Cincinnati'],
                         ['University Of Texas At San Antonio'],
                         ['Georgetown University',
                          'Georgetown'],
                         ['University Of California, Santa Cruz',
                          'University Of Santa Cruz',
                          'University Of Californa, Santa Cruz',
                          'UC Santa Cruz'],
                         ['U Of Pitt',
                          'U Of Pittsburgh',
                          'University Of Pittsburgh',
                          'University Of Pittsburg',
                          'The University Of Pittsburgh'],
                         ['University Of Victoria'],
                         ['Temple University'],
                         ['University Of Illinois, Chicago',
                          'University Of Illinois At Chicago'],
                         ['University Of Wyoming'],
                         ['Indiana University'],
                         ['York University'],
                         ['Villanova University',
                          'Villanova'],
                         ['University Of Rochester'],
                         ['University Of Pennsylvania GSE',
                          'Penn GSE'],
                         ['North Dakota State University'],
                         ['University Of Maryland',
                          'University Of Maryland, College Park',
                          'U Maryland'],
                         ['Western Michigan University'],
                         ['University Of Alberta',
                          'Alberta'],
                         ['The University Of Akron',
                          'University Of Akron'],
                         ['Oklahoma State University'],
                         ['University Of Calgary'],
                         ['West Chester University'],
                         ['UFL',
                          'University Of Florida, Gainesville'],
                         ['Hkust'],
                         ['University Of California San Diego',
                          'University Of California, San Diego',
                          'UCSD',
                          'ucsduniversitycaliforniasandiego'],
                         ['Loyola University Chicago',
                          'Loyola Chicago'],
                         ['Texas Agricultural And Machinery University',
                          'Texus A'],
                         ['Auburn University'],
                         ['Utah State University'],
                         ['Arizona State  University',
                          'Arizona State University'],
                         ['Lehigh University'],
                         ['Syracuse University'],
                         ['Katholieke Universiteit Leuven'],
                         ['Washington State University'],
                         ['American University'],
                         ['Southern Methodist University',
                          'South Methodist U'],
                         ['University Of Delaware'],
                         ['George Mason  University',
                          'George Mason University'],
                         ['Colorado State University,Fort Collins'],
                         ['The University Of Warwick'],
                         ['NYU Stern'],
                         ['California State University, East Bay'],
                         ['Tulane University'],
                         ['UC Berkeley School Of Public Health'],
                         ['University Of Nebraska Lincoln'],
                         ['Yale School Of Engineering And Applied Science'],
                         ['Emory University Rollins School Of Public Health'],
                         ['TAMU'],
                         ['UNLV'],
                         ['Universite De Montreal'],
                         ['Brown University',
                          'BrownUniversity',
                          'Brown'],
                         ['Georgia State University'],
                         ['Rutgers University Graduate School Of Education'],
                         ['Imperial College London',
                          'ImperialCollegeLondon',
                          'ICL'],
                         ['GeorgiaTech',
                          'Georgia Institute of Technology',
                          'GATech'],
                         ['Northeastern University',
                          'Northeastern',
                          'Northeastern University, Boston']
                         ]

alternative_name_list = map(lambda x: map(
    clean_string, x), alternative_name_list)


def univ_name(x):
    x = clean_string(x)
    for name_list in alternative_name_list:
        if x in name_list:
            return name_list[0]
            break
    return x
